from enum import Enum


class DeviceTypes(Enum):
    UNDEFINED, EVC, PHONE, HEADPHONES, LAPTOP = list(range(0, 5))


class EVCStatus(Enum):
    AUTHORIZATION, CHARGE_POINT, FIRMWARE_UPDATE, CHARGE_SESSION, CURRENT_CHARGE_SESSION, \
    CACHED_CHARGE_SESSION, DELAY_CHARGE_REMAINING_TIME, MASTER_CARD, USER_CARD, \
    METRICS, MIN_CURRENT, MAX_CURRENT, POWER_OPT_MIN, POWER_OPT_MAX = list(range(0, 14))
